# Generated by Django 5.1.1 on 2026-04-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatgpt", "0005_chatgptaccount_account_type_and_relay_fields"),
        ("accounts", "0003_user_expired_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False, verbose_name="邮箱已验证"),
        ),
        migrations.AddField(
            model_name="user",
            name="plan_id",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="套餐ID"),
        ),
        migrations.AddField(
            model_name="user",
            name="pool_mode",
            field=models.CharField(
                choices=[("public_pool", "站点公共账号池"), ("specific_pools", "指定号池")],
                default="public_pool",
                max_length=32,
                verbose_name="账号池模式",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="quota_snapshot",
            field=models.JSONField(default=dict, verbose_name="额度快照"),
        ),
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[("active", "正常"), ("disabled", "停用"), ("expired", "过期")],
                default="active",
                max_length=32,
                verbose_name="状态",
            ),
        ),
        migrations.CreateModel(
            name="UserPoolBinding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "gptcar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_bindings",
                        to="chatgpt.chatgptcar",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pool_bindings",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "gptcar")},
            },
        ),
    ]
