# Generated by Django 5.1.1 on 2026-04-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_status_userpoolbinding_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicePlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, unique=True, verbose_name="套餐名")),
                ("code", models.CharField(max_length=64, unique=True, verbose_name="套餐编码")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("allow_web", models.BooleanField(default=True, verbose_name="网页可用")),
                ("allow_api", models.BooleanField(default=True, verbose_name="API 可用")),
                ("monthly_price", models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="月费")),
                ("display_order", models.PositiveIntegerField(default=100, verbose_name="排序")),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                ("created_at", models.IntegerField(blank=True, db_index=True, verbose_name="创建时间")),
                ("updated_at", models.IntegerField(blank=True, db_index=True, verbose_name="修改时间")),
            ],
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "生效中"), ("expired", "已过期"), ("canceled", "已取消")],
                        default="active",
                        max_length=32,
                        verbose_name="状态",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="生效时间")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="结束时间")),
                ("quota_snapshot", models.JSONField(default=dict, verbose_name="额度快照")),
                ("created_at", models.IntegerField(blank=True, db_index=True, verbose_name="创建时间")),
                ("updated_at", models.IntegerField(blank=True, db_index=True, verbose_name="修改时间")),
                (
                    "service_plan",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subscriptions", to="accounts.serviceplan"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subscriptions", to="accounts.user"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuotaRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("model_name", models.CharField(blank=True, max_length=128, verbose_name="模型名")),
                (
                    "channel",
                    models.CharField(
                        choices=[("all", "全部"), ("web", "网页"), ("api", "API")],
                        default="all",
                        max_length=16,
                        verbose_name="渠道",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[("daily", "每日"), ("monthly", "每月")],
                        default="monthly",
                        max_length=16,
                        verbose_name="周期",
                    ),
                ),
                ("request_limit", models.PositiveIntegerField(default=0, verbose_name="请求上限")),
                ("token_limit", models.PositiveIntegerField(default=0, verbose_name="Token 上限")),
                ("enabled", models.BooleanField(default=True, verbose_name="启用")),
                ("remark", models.CharField(blank=True, max_length=255, verbose_name="备注")),
                ("created_at", models.IntegerField(blank=True, db_index=True, verbose_name="创建时间")),
                ("updated_at", models.IntegerField(blank=True, db_index=True, verbose_name="修改时间")),
                (
                    "service_plan",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="quota_rules", to="accounts.serviceplan"),
                ),
            ],
        ),
    ]
