# Generated by Django 5.1.1 on 2026-04-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_serviceplan_usersubscription_quotarule"),
    ]

    operations = [
        migrations.CreateModel(
            name="GatewayUserDailyUsage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("stat_date", models.DateField(db_index=True, verbose_name="统计日期")),
                ("request_count", models.PositiveIntegerField(default=0, verbose_name="累计请求数")),
                ("source", models.CharField(default="gateway_user_use_count", max_length=64, verbose_name="来源")),
                ("created_at", models.IntegerField(blank=True, db_index=True, verbose_name="创建时间")),
                ("updated_at", models.IntegerField(blank=True, db_index=True, verbose_name="修改时间")),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="gateway_daily_usages", to="accounts.user"),
                ),
            ],
            options={
                "unique_together": {("user", "stat_date")},
            },
        ),
    ]
