# Generated by Django 5.1.1 on 2026-04-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatgpt", "0004_chatgptaccount_auth_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatgptaccount",
            name="account_type",
            field=models.CharField(
                choices=[("chatgpt_token", "ChatGPT Token"), ("relay_api", "Relay URL + Key")],
                default="chatgpt_token",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="chatgptaccount",
            name="relay_api_key",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatgptaccount",
            name="relay_base_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="chatgptaccount",
            name="access_token",
            field=models.TextField(blank=True),
        ),
    ]
