# Generated by Django 5.1.1 on 2026-04-04

from django.db import migrations, models


def backfill_source_type(apps, schema_editor):
    ChatgptAccount = apps.get_model("chatgpt", "ChatgptAccount")
    ChatgptAccount.objects.filter(account_type="relay_api").update(source_type="relay")


class Migration(migrations.Migration):

    dependencies = [
        ("chatgpt", "0005_chatgptaccount_account_type_and_relay_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatgptaccount",
            name="enabled_for_api",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="chatgptaccount",
            name="enabled_for_web",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="chatgptaccount",
            name="health_status",
            field=models.CharField(
                choices=[("healthy", "健康"), ("degraded", "降级"), ("down", "停用")],
                default="healthy",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="chatgptaccount",
            name="max_concurrency",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="chatgptaccount",
            name="priority",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="chatgptaccount",
            name="rpm_limit",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chatgptaccount",
            name="source_type",
            field=models.CharField(
                choices=[("official", "官方账号"), ("relay", "中转站")],
                default="official",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="chatgptaccount",
            name="supported_models",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="chatgptaccount",
            name="tpm_limit",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chatgptaccount",
            name="unit_cost",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="chatgptaccount",
            name="weight",
            field=models.IntegerField(default=1),
        ),
        migrations.RunPython(backfill_source_type, migrations.RunPython.noop),
    ]
