# Generated by Django 5.1.1 on 2026-04-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_status_userpoolbinding_and_more"),
        ("chatgpt", "0006_chatgptaccount_dispatch_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="DispatcherDecisionLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("entrypoint", models.CharField(blank=True, max_length=64, verbose_name="入口")),
                ("channel", models.CharField(max_length=16, verbose_name="渠道")),
                ("model_name", models.CharField(blank=True, max_length=128, verbose_name="请求模型")),
                (
                    "decision_status",
                    models.CharField(
                        choices=[("selected", "已选中"), ("empty", "无可用账号"), ("rejected", "请求被拒绝")],
                        default="selected",
                        max_length=32,
                        verbose_name="调度结果",
                    ),
                ),
                ("requested_account_id", models.PositiveIntegerField(blank=True, null=True, verbose_name="请求账号 ID")),
                ("candidate_account_ids", models.JSONField(default=list, verbose_name="候选账号列表")),
                ("reason", models.TextField(blank=True, verbose_name="调度说明")),
                ("created_time", models.IntegerField(blank=True, db_index=True, verbose_name="创建时间")),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatcher_logs",
                        to="chatgpt.chatgptaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatcher_logs",
                        to="accounts.user",
                    ),
                ),
            ],
        ),
    ]
