# Generated by Django 5.1.1 on 2026-04-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatgpt", "0007_dispatcherdecisionlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsageLedger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("model_name", models.CharField(blank=True, max_length=128, verbose_name="模型名")),
                ("request_type", models.CharField(max_length=64, verbose_name="请求类型")),
                ("prompt_tokens", models.PositiveIntegerField(default=0, verbose_name="输入 Tokens")),
                ("completion_tokens", models.PositiveIntegerField(default=0, verbose_name="输出 Tokens")),
                ("total_tokens", models.PositiveIntegerField(default=0, verbose_name="总 Tokens")),
                ("estimated_cost", models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name="预估成本")),
                ("status_code", models.PositiveIntegerField(default=0, verbose_name="状态码")),
                ("error_code", models.CharField(blank=True, max_length=128, verbose_name="错误码")),
                ("created_at", models.IntegerField(blank=True, db_index=True, verbose_name="创建时间")),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_ledgers",
                        to="chatgpt.chatgptaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_ledgers",
                        to="accounts.user",
                    ),
                ),
            ],
        ),
    ]
