# Generated by Django 5.1.1 on 2026-04-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_gatewayuserdailyusage"),
        ("chatgpt", "0008_usageledger"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatConversation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(default="新对话", max_length=160, verbose_name="会话标题")),
                ("model_name", models.CharField(blank=True, max_length=128, verbose_name="默认模型")),
                ("preview_text", models.TextField(blank=True, verbose_name="预览内容")),
                ("message_count", models.PositiveIntegerField(default=0, verbose_name="消息数量")),
                ("last_message_at", models.IntegerField(db_index=True, default=0, verbose_name="最后消息时间")),
                ("created_time", models.IntegerField(blank=True, db_index=True, verbose_name="创建时间")),
                ("updated_time", models.IntegerField(blank=True, db_index=True, verbose_name="更新时间")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_conversations",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_time", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ChatConversationMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "用户"), ("assistant", "助手"), ("system", "系统")],
                        max_length=16,
                        verbose_name="消息角色",
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="消息内容")),
                ("account_label", models.CharField(blank=True, max_length=128, verbose_name="通道标签")),
                ("sequence", models.PositiveIntegerField(db_index=True, default=0, verbose_name="排序序号")),
                ("created_time", models.IntegerField(blank=True, db_index=True, verbose_name="创建时间")),
                ("updated_time", models.IntegerField(blank=True, db_index=True, verbose_name="更新时间")),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chatgpt.chatconversation",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence", "id"),
            },
        ),
    ]
