# Generated by Django 5.1.1 on 2026-04-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatgpt", "0009_chatconversation_chatconversationmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatconversation",
            name="reasoning_effort",
            field=models.CharField(blank=True, max_length=32, verbose_name="思考等级"),
        ),
        migrations.AddField(
            model_name="chatconversationmessage",
            name="content_blocks",
            field=models.JSONField(blank=True, default=list, verbose_name="内容块"),
        ),
    ]
